import { Asset, BacktestScenario } from "./types";

export const DEFAULT_ASSETS: Asset[] = [
  {
    id: "1",
    symbol: "AAPL",
    name: "Apple Inc.",
    type: "Stock",
    quantity: 15,
    costBasis: 165.0,
    currentPrice: 189.3,
    sector: "Technology",
  },
  {
    id: "2",
    symbol: "BTC",
    name: "Bitcoin",
    type: "Crypto",
    quantity: 0.35,
    costBasis: 38500.0,
    currentPrice: 63800.0,
    sector: "Cryptocurrency",
  },
  {
    id: "3",
    symbol: "VOO",
    name: "Vanguard S&P 500 ETF",
    type: "ETF",
    quantity: 8,
    costBasis: 415.0,
    currentPrice: 485.6,
    sector: "Broad Market",
  },
  {
    id: "4",
    symbol: "BND",
    name: "Vanguard Total Bond Market",
    type: "Bond",
    quantity: 25,
    costBasis: 72.5,
    currentPrice: 73.1,
    sector: "Fixed Income",
  },
  {
    id: "5",
    symbol: "CASH",
    name: "US Dollar Cash",
    type: "Cash",
    quantity: 1800,
    costBasis: 1.0,
    currentPrice: 1.0,
    sector: "Cash Equivalents",
  },
];

export const AVAILABLE_SECTORS = [
  "Technology",
  "Cryptocurrency",
  "Broad Market",
  "Fixed Income",
  "Cash Equivalents",
  "Healthcare",
  "Financials",
  "Consumer Discretionary",
  "Energy",
  "Real Estate",
  "Utilities",
  "Other",
];

export const SCENARIOS: BacktestScenario[] = [
  {
    id: "gfc_2008",
    name: "2008 Great Recession",
    period: "18 Months (2007-2009)",
    description: "The subprime mortgage meltdown trigger. Massive global equity crash, fixed-income yields compression, extreme capital flight to cash safety.",
    impacts: {
      Stock: -42,
      Crypto: 0, // Unaffected (didn't exist)
      ETF: -38,
      "Mutual Fund": -38,
      Bond: 6,
      Cash: 0,
      Other: -20,
      Technology: -45,
      Cryptocurrency: 0,
      "Broad Market": -38,
      "Fixed Income": 6,
      "Cash Equivalents": 0,
      Healthcare: -20,
      Financials: -65,
      "Consumer Discretionary": -40,
      Energy: -35,
      "Real Estate": -55,
      Utilities: -15,
    },
  },
  {
    id: "covid_2020",
    name: "2020 COVID-19 Panic & QE Rally",
    period: "12 Months (2020)",
    description: "An initial high-velocity crash followed by a massive liquidity injection and retail surge, causing unprecedented technology and crypto bull runs.",
    impacts: {
      Stock: 22,
      Crypto: 140,
      ETF: 18,
      "Mutual Fund": 16,
      Bond: 8,
      Cash: 0,
      Other: 10,
      Technology: 48,
      Cryptocurrency: 140,
      "Broad Market": 18,
      "Fixed Income": 8,
      "Cash Equivalents": 0,
      Healthcare: 30,
      Financials: -5,
      "Consumer Discretionary": 25,
      Energy: -20,
      "Real Estate": 5,
      Utilities: 2,
    },
  },
  {
    id: "inflation_2022",
    name: "2022 Fed Rate-Hiking & Inflation",
    period: "12 Months (2022)",
    description: "High inflation forces the Federal Reserve to aggressively raise interest rates. Both stock multiples contract and bond prices suffer record losses.",
    impacts: {
      Stock: -19,
      Crypto: -64,
      ETF: -18,
      "Mutual Fund": -18,
      Bond: -13,
      Cash: 0,
      Other: -10,
      Technology: -33,
      Cryptocurrency: -64,
      "Broad Market": -18,
      "Fixed Income": -13,
      "Cash Equivalents": 0,
      Healthcare: -4,
      Financials: -12,
      "Consumer Discretionary": -38,
      Energy: 54, // Energy was a massive hedge in 2022!
      "Real Estate": -26,
      Utilities: -1,
    },
  },
  {
    id: "ai_rally_2024",
    name: "AI Euphoria & Tech Dominance",
    period: "12 Months (2024)",
    description: "Massive generative AI developments push tech giants to record valuations. Mainstream Bitcoin ETF approvals spark a strong cryptocurrency revival.",
    impacts: {
      Stock: 28,
      Crypto: 95,
      ETF: 24,
      "Mutual Fund": 22,
      Bond: 2,
      Cash: 4.5, // High yields
      Other: 12,
      Technology: 52,
      Cryptocurrency: 95,
      "Broad Market": 24,
      "Fixed Income": 2,
      "Cash Equivalents": 4.5,
      Healthcare: 8,
      Financials: 18,
      "Consumer Discretionary": 15,
      Energy: -5,
      "Real Estate": 6,
      Utilities: 14,
    },
  },
];
